# Generated by Django 2.2.5 on 2019-11-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0002_auto_20191102_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
